INSERT INTO shows (name, genre, rating, airing) VALUES
  ('Downton Abbey', 'Drama', 90, true),
  ('Doc Martin', 'Comedy', 85, false),
  ('Sopranos', 'Drama', 80, false),
  ('NCIS', 'Drama', 65, true),
  ('Battlestar Galactica', 'Science Fiction', 75, false),
  ('Orange Is the New Black', 'Drama', 85, true),
  ('Puggle Pops', 'Children', 50, false),
  ('Squidbillies', 'Cartoons', 80, true),
  ('Hockey Night In Canada', 'Sports', 98, true),
  ('Chibi-Rocks', 'Music', 30, false);
